# Generated by Django 5.2.7 on 2025-11-06 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoReporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='evidencias/')),
                ('fechaSubida', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GrupoDuplicado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaDeteccion', models.DateTimeField(auto_now_add=True)),
                ('razon', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PrioridadReporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('bache', 'Bache o hueco'), ('fisura', 'Fisura o grieta'), ('hundimiento', 'Hundimiento de vía'), ('desprendimiento', 'Desprendimiento de capa asfáltica'), ('inundacion', 'Inundación o encharcamiento'), ('obstruccion', 'Obstrucción en la calzada'), ('otro', 'Otro')], max_length=30)),
                ('titulo', models.CharField(max_length=100)),
                ('duplicado', models.BooleanField(default=False)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='reportes/fotos/')),
                ('video', models.FileField(blank=True, null=True, upload_to='reportes/videos/')),
                ('direccion', models.CharField(help_text='Ejemplo: Calle 72 #43-85', max_length=255)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('fechaActualizacion', models.DateTimeField(auto_now=True)),
                ('estado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='reportes.estadoreporte')),
                ('grupoDuplicado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reportes.grupoduplicado')),
                ('prioridad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='reportes.prioridadreporte')),
            ],
        ),
    ]
