# Generated by Django 5.2.7 on 2025-10-06 22:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('bache', 'Bache o hueco'), ('fisura', 'Fisura o grieta'), ('hundimiento', 'Hundimiento de vía'), ('desprendimiento', 'Desprendimiento de capa asfáltica'), ('inundacion', 'Inundación o encharcamiento'), ('obstruccion', 'Obstrucción en la calzada'), ('otro', 'Otro')], max_length=30)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='reportes/fotos/')),
                ('video', models.FileField(blank=True, null=True, upload_to='reportes/videos/')),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
