# Generated by Django 5.2.7 on 2025-10-06 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporte',
            name='latitud',
        ),
        migrations.RemoveField(
            model_name='reporte',
            name='longitud',
        ),
        migrations.AddField(
            model_name='reporte',
            name='direccion',
            field=models.CharField(default='Barranquilla', help_text='Ejemplo: Calle 72 #43-85', max_length=255),
            preserve_default=False,
        ),
    ]
