# Generated by Django 5.2.7 on 2025-11-20 04:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoReporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Estado de Reporte',
                'verbose_name_plural': 'Estados de Reporte',
            },
        ),
        migrations.CreateModel(
            name='GrupoDuplicado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaDeteccion', models.DateTimeField(auto_now_add=True)),
                ('razon', models.TextField()),
            ],
            options={
                'verbose_name': 'Grupo Duplicado',
                'verbose_name_plural': 'Grupos Duplicados',
            },
        ),
        migrations.CreateModel(
            name='PrioridadReporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('nivel_gravedad', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Prioridad de Reporte',
                'verbose_name_plural': 'Prioridades de Reporte',
                'ordering': ['nivel_gravedad'],
            },
        ),
        migrations.CreateModel(
            name='RegistroAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.CharField(max_length=100)),
                ('metadatos', models.JSONField(blank=True, default=dict)),
                ('fecha_evento', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Auditoría',
                'verbose_name_plural': 'Registros de Auditoría',
                'ordering': ['-fecha_evento'],
            },
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('bache', 'Bache o hueco'), ('fisura', 'Fisura o grieta'), ('hundimiento', 'Hundimiento de vía'), ('desprendimiento', 'Desprendimiento de capa asfáltica'), ('inundacion', 'Inundación o encharcamiento'), ('obstruccion', 'Obstrucción en la calzada'), ('otro', 'Otro')], max_length=30)),
                ('descripcion', models.TextField()),
                ('latitud', models.DecimalField(blank=True, decimal_places=7, help_text='Latitud GPS', max_digits=10, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=7, help_text='Longitud GPS', max_digits=10, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('duplicado', models.BooleanField(default=False)),
                ('reportado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reportes.estadoreporte')),
                ('grupoDuplicado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes', to='reportes.grupoduplicado')),
                ('prioridad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reportes.prioridadreporte')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
                'ordering': ['-reportado_en'],
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(choices=[('email', 'Correo Electrónico'), ('sms', 'SMS'), ('push', 'Notificación Push'), ('app', 'In-App')], max_length=20)),
                ('mensaje', models.TextField()),
                ('leido', models.BooleanField(default=False)),
                ('enviado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
                ('reporte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='reportes.reporte')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-enviado_en'],
            },
        ),
        migrations.CreateModel(
            name='HistorialReporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=255)),
                ('detalles', models.TextField()),
                ('fecha_accion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='reportes.reporte')),
            ],
            options={
                'verbose_name': 'Historial de Reporte',
                'verbose_name_plural': 'Historial de Reportes',
                'ordering': ['-fecha_accion'],
            },
        ),
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evidencia', models.CharField(choices=[('foto', 'Fotografía'), ('video', 'Video'), ('documento', 'Documento')], max_length=20)),
                ('archivo', models.FileField(upload_to='evidencias/%Y/%m/%d/')),
                ('url_almacenamiento', models.URLField(blank=True, max_length=500)),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('tamano_bytes', models.BigIntegerField(default=0)),
                ('fechaSubida', models.DateTimeField(auto_now_add=True)),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='reportes.reporte')),
            ],
            options={
                'verbose_name': 'Evidencia',
                'verbose_name_plural': 'Evidencias',
            },
        ),
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('notas', models.TextField(blank=True)),
                ('asignado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones_creadas', to=settings.AUTH_USER_MODEL)),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_tecnico', to=settings.AUTH_USER_MODEL)),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='reportes.reporte')),
            ],
            options={
                'verbose_name': 'Asignación',
                'verbose_name_plural': 'Asignaciones',
            },
        ),
        migrations.AddIndex(
            model_name='reporte',
            index=models.Index(fields=['estado', 'prioridad'], name='reportes_re_estado__f52502_idx'),
        ),
        migrations.AddIndex(
            model_name='reporte',
            index=models.Index(fields=['latitud', 'longitud'], name='reportes_re_latitud_348d0c_idx'),
        ),
    ]
