# Generated by Django 5.2.7 on 2025-11-10 21:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reportes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion',
            name='asignado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='tecnico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_tecnico', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historialreporte',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registroauditoria',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reporte',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reportes.estadoreporte'),
        ),
        migrations.AddField(
            model_name='reporte',
            name='grupoDuplicado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes', to='reportes.grupoduplicado'),
        ),
        migrations.AddField(
            model_name='reporte',
            name='prioridad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reportes.prioridadreporte'),
        ),
        migrations.AddField(
            model_name='reporte',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='reporte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='reportes.reporte'),
        ),
        migrations.AddField(
            model_name='historialreporte',
            name='reporte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='reportes.reporte'),
        ),
        migrations.AddField(
            model_name='evidencia',
            name='reporte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='reportes.reporte'),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='reporte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='reportes.reporte'),
        ),
        migrations.AddIndex(
            model_name='reporte',
            index=models.Index(fields=['estado', 'prioridad'], name='reportes_re_estado__f52502_idx'),
        ),
        migrations.AddIndex(
            model_name='reporte',
            index=models.Index(fields=['latitud', 'longitud'], name='reportes_re_latitud_348d0c_idx'),
        ),
    ]
