# Generated by Django 5.2.7 on 2025-11-20 04:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='evidencia',
            name='es_evidencia_reparacion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='evidencia',
            name='subida_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidencias_subidas', to=settings.AUTH_USER_MODEL),
        ),
    ]
