# Generated by Django 5.2.7 on 2025-11-10 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='direccion',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Latitud GPS', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Longitud GPS', max_digits=10, null=True),
        ),
    ]
